[project]
name = "brekel"
description = "Nodes to enhance & streamline prompts. Enhance using local LLM within ComfyUI, generate using random lines from text files, or randomly select text file prompts, or step through one prompt per line in a text file. Resolution selector with common presets, Load Image node with filename output, Save Image node with PNG/JPG, gap-filling numbering and caption metadata. Queue ETA node that estimates how long the rest of the queue will take."
version = "1.5.0"
license = {file = "LICENSE"}
dependencies = ["bitsandbytes", "accelerate"]

[project.urls]
Repository = "https://github.com/Brekel/ComfyUI-Brekel"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "brekel"
DisplayName = "ComfyUI-Brekel"
Icon = ""
includes = []
